# Generated by Django 3.2.3 on 2021-08-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='self_introduction',
            field=models.CharField(blank=True, default='自己紹介欄', max_length=300, null=True, verbose_name='自己紹介'),
        ),
    ]
