# Generated by Django 3.2.3 on 2021-08-09 03:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_rename_agree_userpolicy_accept'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='通報カテゴリ名')),
            ],
            options={
                'db_table': 'report_category',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.reportcategory', verbose_name='通報カテゴリ'),
        ),
    ]
