# Generated by Django 3.2.3 on 2021-08-10 02:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_auto_20210809_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='target',
            field=models.CharField(default=datetime.datetime(2021, 8, 10, 2, 46, 46, 89315, tzinfo=utc), max_length=500, verbose_name='通報対象'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=500, verbose_name='動画説明文'),
        ),
    ]
